


# Inserts a blank line between shell prompts
add_newline = true

[status]
disabled = false

#[hostname]
#ssh_only = false
#format =  "[$user]@[$hostname](bold red) "
#trim_at = ".companyname.com"
#disabled = false

[cmd_duration]
min_time = 499
format = "took [$duration](bold yellow)"


[custom.svn]
command = "svn info | grep -E 'Revision:[ ]+[0-9]+' | cut -f 2 -d ':' "
when = 'svn info'
format = 'at rev [$output](bold blue) '

#[custom.ENV]
#command = "echo $ENV"
#when = 'test "$ENV" != "" '
#format = "with env [$output](bold purple) "


[env_var.ENV]
variable = 'ENV'
format = "with env [$env_value](bold purple) "

