# espanso configuration file
# This is the default configuration file, change it as you like it

# You can refer to the official documentation: [https://espanso.org/docs/]
# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

matches:
#text matches
  - trigger: ";m;"
    fast_inject: false
    replace: "```"
# - trigger: ";m;"
#    replace: "\u0060\u0060\u0060"
# Emoji
  - trigger: ":monocle:"
    replace: "🧐"
  - trigger: ":nice:"
    replace: "👌"

  - trigger: ";clipboard"
    replace: "{{clipboard}}"
    backend: Inject
    fast_inject: false
    vars:
      - name: "clipboard"
        type: "clipboard"

# Shell commands (template)
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
# Shell
  - trigger: ":filler:"
    replace: "{{res}}"
    vars:
      - name: res
        type: shell
        params:
          cmd: "base64 /dev/urandom | awk '{print(0==NR%10)?\"\":$1}' | sed 's/[^[:alpha:]]/ /g' | head -10"

  - trigger: ":mb:"
    replace: "```{{clipboard}}```"
    vars:
      - name: "clipboard"
        type: "clipboard"
